### ISSUE TITLE
Can't get back to root from diving into group

### ISSUE THREAD

**Issue by d9k** [methodofaction/Method-Draw#105]
For current version of https://editor.method.ac/ (probably https://github.com/methodofaction/Method-Draw/tree/a87309c0809d9289c794df28cb4e3b1c8bf9f4a4 ?)

1) draw two overlapping rectangles

![Screenshot from 2021-03-17 20-43-16](https://user-images.githubusercontent.com/7331988/111513279-af721980-8761-11eb-8c5e-f75be8e54f36.png)

2) select them both (by "rubber band" or with shift+click)
3) Menu item `Object->Group` doesn't work!! Click does nothing
4) So group them with `ctrl+g`
5) Dive into group by double click to grouped elements

![Screenshot from 2021-03-17 20-44-46](https://user-images.githubusercontent.com/7331988/111513582-01b33a80-8762-11eb-92a5-14e40ddf40d3.png)

6) Can't get back by click to the `Layer 1` link on the top left corner!

@methodofaction, please fix menu ( `3.` ) and breadcrumbs ( `6.` ).

**Comment by grapheine** [comment]
me too...

**Comment by methodofaction** [comment]
@d9k @grapheine This is fixed, thanks for the detailed report.
