### ISSUE TITLE
Feature Request: Properties panel key/value

### ISSUE THREAD

**Issue by kleinmantara** [methodofaction/Method-Draw#109]
Hi,
thank you for your great work. I would like to add a properties panel (key / value) to the right panel area. The user can create his own key / value pairs. The key / value pairs are then stored directly on the object as a "data-prop- *" attribute.

@methodofaction do you have an idea how to do that best?

Here is an example (from openstreetmap):
![image](https://user-images.githubusercontent.com/22788087/112688922-d9ba8a00-8e79-11eb-9a31-5275c42d61f1.png)

**Comment by methodofaction** [comment]
Hire me to implement it.
