### ISSUE TITLE
Export as PNG not work

### ISSUE THREAD

**Issue by maxmas** [methodofaction/Method-Draw#15]
I click Export as PNG then open a new window,
but no PNG file.
Why? is it my mistake?

My system environment:
XP Pro SP3
Google Chrome V.29.0.1547.66 m

![method-draw](https://f.cloud.github.com/assets/1468763/1136366/656530b0-1c3f-11e3-902d-435437b0827a.jpg)

**Comment by sardbaba** [comment]
thanks @Merenon

**Comment by methodofaction** [comment]
Works now by downloading
