### ISSUE TITLE
editor.method.ac is not accessible

### ISSUE THREAD

**Issue by plKamilPawlik** [methodofaction/Method-Draw#159]
I have noticed, that the website is not accessible via internet. I do not know if anyone has noticed. Also, I have not seen any updates from your site about planed downtimes.

![image](https://github.com/methodofaction/Method-Draw/assets/69432182/a3f47f8e-f8d2-4cf6-b6ed-9eb4e6b94df8)

**Comment by methodofaction** [comment]
@plkpawlik thanks for the notice, it was announced on my Twitter account that everything under *.method.ac would have a downtime that weekend due to a domain renewal issue.
