### ISSUE TITLE
Problems with getScreenCTM or getCTM (position of the cursor) in Firefox

### ISSUE THREAD

**Issue by tmontanaro** [methodofaction/Method-Draw#20]
In Firefox, if I try to draw a line in the top left corner of the screen, the line is drawn starting from the center of the page. I have already tried with other browsers, and the problem does not exist, however, I have already tried to contact Firefox developers and they answer:
<<
The editor is buggy. It's using getScreenCTM or getCTM incorrectly. Contact the author and ask him or her to fix it.

> > (As you can see here: https://bugzilla.mozilla.org/show_bug.cgi?id=1029805 )

**Comment by methodofaction** [comment]
This works correctly now
