### ISSUE TITLE
Object rotate after new Document

### ISSUE THREAD

**Issue by MichaelKoch** [methodofaction/Method-Draw#34]
Hi ,
the Editor has Problems to rotate ( i.e. circle)  elements after 
create New Document .

To reproduce:

http://editor.method.ac/
     --> Draw Circle 
      --> Menu --> File --> New Document 
     --> Draw Circle 
     --> Try to rotate 
I would be happy if this bug will be fixed . 

kind regards

Michael

**Comment by duopixel** [comment]
Acknowledged, can't say when this will be fixed but I'll take a look soon.

**Comment by nicholaswmin** [comment]
@MichaelKoch Can you still reproduce this?

**Comment by methodofaction** [comment]
Can't reproduce anymore
