### ISSUE TITLE
Packaging for Sandstorm

### ISSUE THREAD

**Issue by zeigerpuppy** [methodofaction/Method-Draw#55]
I'd like to try packaging Method-Draw for Sandstorm (https://sandstorm.io).
One issue that would need to be solved first is how to save the SVG files in a persistent way (not only in the localstorage).
Is there a method for writing back to the server that could be relatively easily implemented in the current framework?

**Comment by marcelklehr** [comment]
Hey @zeigerpuppy! I've written a real-time collaboration platform that integrates MethodDraw (among other editors and document types). All revisions are persistently stored on the server. Try it at [hive.js](https://hivejs.org) ;) -- it would be cool to integrate it into sandstorm!

**Comment by zeigerpuppy** [comment]
Hi @marcelklehr, That's great, I'd definitely like to have a look at what you've done with hivejs.
It looks like there could be some really good crossover in getting applications working in the different environments.  Did you do much modification of the source for method-draw?

**Comment by marcelklehr** [comment]
I deactivate the menu bar using externally injected css, but other than that Method-Draw runs in hive.js as-is, requiring no modifications (I simply include it as a git submodule).

**Comment by zeigerpuppy** [comment]
Hi @marcelklehr, did you make any progress with hivejs?  I note that the domain is no longer active.  I'd like to give it a go at packaging again if the source is still available.

**Comment by marcelklehr** [comment]
@zeigerpuppy Hey :) I did make some progress, but mainly moved away from building a full-featured ready-to-run app towards [a more modular approach](https://github.com/gulf/gulf). I've moved away from Operational transforms however, since CRDTs are around, because I felt that CRDTs are much more adept for this kind of thing and there's other people doing a better job than I was. So, gulf and hive.js is currently abandonware :/

**Comment by zeigerpuppy** [comment]
Very interesting... I have just been doing a(nother) deep dive into current online SVG editor projects.
It looks like there's nothing out there that meets the following criteria yet:
- real-time collaborative SVG
- import and export of SVG while retaining groups and layers
- self-hosted

In fact, not even the commercial products do this very well (see for instance https://vecta.io - which is about the closest but seems to mangle SVG layers on import).

[Spacedeck](https://github.com/spacedeck/spacedeck-open) uses SVG under the hood but doesn't support layers or SVG export (it does have collaborative editing and a simple SVG import).
There's also the draw.io port for sandstorm, but that's not collaborative and also only has simple SVG import (but good SVG export)

It would be great to package up some sort of SVG editor for sandstorm eventually...

**Comment by marcelklehr** [comment]
What about OnlyOffice/Collabora's Draw?

IMHO, building something like this should be close to trivial when using OT or CRDTs to sync the XML of the SVG document.

**Comment by zeigerpuppy** [comment]
As far as I can see neither Collabora or OnlyOffice support SVG formats, but a good idea to explore those further.

It does seem like SVG should work well with CRDTs, I think this combo could be a really useful application (collaborative wireframing is an immediately obvious use case for example).  From my perspective, pure SVG has so many advantages (not least of which is that it's declarative and compatible with version management).
