### ISSUE TITLE
Multi line text

### ISSUE THREAD

**Issue by mysimpex** [methodofaction/Method-Draw#63]
The text editor control only accepts a single line. Is it possible to have it accept multi-line text?

**Comment by XinoSoft** [comment]
The text editor control only accepts a single line. Is it possible to have it accept multi-line text?

**Comment by sachin-rebelute** [comment]
We are also facing the same issue. Anyone get solution for this? 
Thanks in advance.

**Comment by methodofaction** [comment]
Would take months of development.

**Comment by artursopelnik** [comment]
+1
