### ISSUE TITLE
Lack attribute when import saved svg file

### ISSUE THREAD

**Issue by lanqiuzf** [methodofaction/Method-Draw#74]
when i created a svg file, i put attribute 'label' in it. And i changed the saved function to make the label attribute code in file. for example, like 'label="xxxxxx"'.
However, when i import this svg file, the attribute missed.
The attachment is the example.

![example](https://user-images.githubusercontent.com/22518154/44330951-de855900-a49a-11e8-8d35-1ddb2ea5ee02.png)

**Comment by xiumuzidiao-lu** [comment]
path数据得到

**Comment by methodofaction** [comment]
@lanqiuzf Method Draw cleans up certain attributes upon importation.
