### ISSUE TITLE
unable to use undo( ) in embedded iframe mode  

### ISSUE THREAD

**Issue by attachaudhury** [methodofaction/Method-Draw#83]
I am using Method-Draw embedded iframe. I want to undo from some external button
`var frame = document.getElementById('svgedit');`
 `var svgCanvas = new embedded_svg_edit(frame);`
`svgCanvas.setSvgString("some svg");  //this is working fine`
`svgCanvas.undo();  //this gives me error`

Uncaught SyntaxError: Unexpected token ':'
    at embedapi.js:117

**Comment by methodofaction** [comment]
@attachaudhury embedded iframe mode is not supported
